# Dockerfile
FROM python:3.12-slim



WORKDIR /app

# sistem deps (opsional, tambahkan jika perlu build wheels)
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# copy requirements first for docker layer caching
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy application code
COPY . .

# expose port (container internal)
EXPOSE 8000

# jalankan uvicorn
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
